export function generateWindowsDebugRuntimeCode(): string {
  let result = ''
  result += 'static long long yc_dbg_read_cmd_token(void) {\n'
  result += '    FILE* fp = _wfopen(L".ycdbg_cmd", L"rb");\n'
  result += '    if (!fp) return g_yc_dbg_resume_token;\n'
  result += '    char buf[64] = { 0 };\n'
  result += '    size_t n = fread(buf, 1, sizeof(buf) - 1, fp);\n'
  result += '    fclose(fp);\n'
  result += '    buf[n] = 0;\n'
  result += '    return _strtoi64(buf, NULL, 10);\n'
  result += '}\n\n'
  result += 'static void yc_dbg_wait_for_resume(void) {\n'
  result += '    yc_dbg_break_end();\n'
  result += '    for (;;) {\n'
  result += '        long long token = yc_dbg_read_cmd_token();\n'
  result += '        if (token > g_yc_dbg_resume_token) {\n'
  result += '            g_yc_dbg_resume_token = token;\n'
  result += '            break;\n'
  result += '        }\n'
  result += '        MSG msg;\n'
  result += '        while (PeekMessageW(&msg, NULL, 0, 0, PM_REMOVE)) {\n'
  result += '            if (msg.message == WM_QUIT) {\n'
  result += '                PostQuitMessage((int)msg.wParam);\n'
  result += '                return;\n'
  result += '            }\n'
  result += '            TranslateMessage(&msg);\n'
  result += '            DispatchMessageW(&msg);\n'
  result += '        }\n'
  result += '        Sleep(20);\n'
  result += '    }\n'
  result += '}\n\n'
  return result
}
