#include "include_krnln_header.h"

// 系统核心支持库常量定义
// 自动生成于 2026-01-04 15:09:00
// 常量总数: 335

// 常量类型: CT_NULL=空常量, CT_NUM=数值型, CT_BOOL=逻辑型, CT_TEXT=文本型

#ifndef __E_STATIC_LIB

LIB_CONST_INFO g_ConstInfo_krnln_global_var[] = 
{
    {"引号", "", "半角双引号。", 1, CT_NUM, NULL, 0.0},
    {"左引号", "", "全角左双引号。", 1, CT_NUM, NULL, 0.0},
    {"右引号", "", "全角右双引号。", 1, CT_NUM, NULL, 0.0},
    {"换行符", "", "一个回车符（13）和一个换行符（10）的组合。", 1, CT_NUM, NULL, 0.0},
    {"pi", "", "", 1, CT_NUM, NULL, 3.1415926535},
    {"e", "", "", 1, CT_NUM, NULL, 2.718282},
    {"黑色", "black", "常用颜色值。", 1, CT_NUM, NULL, 0.0},
    {"藏青", "", "", 1, CT_NUM, NULL, 8388608.0},
    {"墨绿", "", "", 1, CT_NUM, NULL, 32768.0},
    {"深青", "", "", 1, CT_NUM, NULL, 8421376.0},
    {"红褐", "", "", 1, CT_NUM, NULL, 128.0},
    {"紫红", "", "", 1, CT_NUM, NULL, 8388736.0},
    {"褐绿", "", "", 1, CT_NUM, NULL, 32896.0},
    {"浅灰", "gray", "", 1, CT_NUM, NULL, 12632256.0},
    {"灰色", "", "", 1, CT_NUM, NULL, 8421504.0},
    {"蓝色", "blue", "", 1, CT_NUM, NULL, 16711680.0},
    {"绿色", "green", "", 1, CT_NUM, NULL, 65280.0},
    {"艳青", "", "", 1, CT_NUM, NULL, 16776960.0},
    {"红色", "red", "", 1, CT_NUM, NULL, 255.0},
    {"品红", "", "", 1, CT_NUM, NULL, 16711935.0},
    {"黄色", "yellow", "", 1, CT_NUM, NULL, 65535.0},
    {"白色", "white", "", 1, CT_NUM, NULL, 16777215.0},
    {"蓝灰", "", "", 1, CT_NUM, NULL, 16744576.0},
    {"藏蓝", "", "", 1, CT_NUM, NULL, 14692440.0},
    {"嫩绿", "", "", 1, CT_NUM, NULL, 57472.0},
    {"青绿", "", "", 1, CT_NUM, NULL, 8445952.0},
    {"黄褐", "", "", 1, CT_NUM, NULL, 24768.0},
    {"粉红", "", "", 1, CT_NUM, NULL, 16754943.0},
    {"嫩黄", "", "", 1, CT_NUM, NULL, 55512.0},
    {"银白", "", "", 1, CT_NUM, NULL, 15527148.0},
    {"紫色", "", "", 1, CT_NUM, NULL, 16711824.0},
    {"天蓝", "", "", 1, CT_NUM, NULL, 16746496.0},
    {"灰绿", "", "", 1, CT_NUM, NULL, 8429696.0},
    {"青蓝", "", "", 1, CT_NUM, NULL, 12607488.0},
    {"橙黄", "", "", 1, CT_NUM, NULL, 33023.0},
    {"桃红", "", "", 1, CT_NUM, NULL, 8409343.0},
    {"芙红", "", "", 1, CT_NUM, NULL, 12615935.0},
    {"深灰", "", "", 1, CT_NUM, NULL, 6316128.0},
    {"透明", "", "", 1, CT_NUM, NULL, -16777216.0},
    {"隐藏窗口", "ShowHide", "", 1, CT_NUM, NULL, 1.0},
    {"普通激活", "ShowNormal", "", 1, CT_NUM, NULL, 2.0},
    {"最小化激活", "ShowMin", "", 1, CT_NUM, NULL, 3.0},
    {"最大化激活", "ShowMax", "", 1, CT_NUM, NULL, 4.0},
    {"普通不激活", "ShowNoActivate", "", 1, CT_NUM, NULL, 5.0},
    {"最小化不激活", "ShowMinNoActivate", "", 1, CT_NUM, NULL, 6.0},
    {"读入", "read", "", 1, CT_NUM, NULL, 1.0},
    {"写出", "write", "", 1, CT_NUM, NULL, 2.0},
    {"读写", "ReadWrite", "", 1, CT_NUM, NULL, 3.0},
    {"重写", "over", "", 1, CT_NUM, NULL, 4.0},
    {"改写", "modi", "", 1, CT_NUM, NULL, 5.0},
    {"改读", "ModiRead", "", 1, CT_NUM, NULL, 6.0},
    {"无限制", "DenyNone", "", 1, CT_NUM, NULL, 1.0},
    {"禁止读", "DenyRead", "", 1, CT_NUM, NULL, 2.0},
    {"禁止写", "DenyWrite", "", 1, CT_NUM, NULL, 3.0},
    {"禁止读写", "DenyReadWrite", "", 1, CT_NUM, NULL, 4.0},
    {"文件首", "FileBegin", "", 1, CT_NUM, NULL, 1.0},
    {"文件尾", "FileEnd", "", 1, CT_NUM, NULL, 2.0},
    {"现行位置", "FileCurrent", "", 1, CT_NUM, NULL, 3.0},
    {"只读文件", "ReadOnlyFile", "", 1, CT_NUM, NULL, 1.0},
    {"隐藏文件", "HiddenFile", "", 1, CT_NUM, NULL, 2.0},
    {"系统文件", "SystemFile", "", 1, CT_NUM, NULL, 4.0},
    {"子目录", "SubDir", "", 1, CT_NUM, NULL, 16.0},
    {"存档文件", "ArcFile", "", 1, CT_NUM, NULL, 32.0},
    {"无属性文件", "NormalFile", "", 1, CT_NUM, NULL, 128.0},
    {"字节型", "byte", "", 1, CT_NUM, NULL, 1.0},
    {"短整数型", "short", "", 1, CT_NUM, NULL, 2.0},
    {"整数型", "int", "", 1, CT_NUM, NULL, 3.0},
    {"长整数型", "int64", "", 1, CT_NUM, NULL, 4.0},
    {"小数型", "float", "", 1, CT_NUM, NULL, 5.0},
    {"双精度小数型", "double", "", 1, CT_NUM, NULL, 6.0},
    {"逻辑型", "bool", "", 1, CT_NUM, NULL, 7.0},
    {"日期时间型", "DateTime", "", 1, CT_NUM, NULL, 8.0},
    {"子程序指针型", "SubPtr", "", 1, CT_NUM, NULL, 9.0},
    {"文本型", "text", "", 1, CT_NUM, NULL, 10.0},
    {"年份", "year", "", 1, CT_NUM, NULL, 1.0},
    {"季度", "quarter", "", 1, CT_NUM, NULL, 2.0},
    {"月份", "month", "", 1, CT_NUM, NULL, 3.0},
    {"周", "week", "", 1, CT_NUM, NULL, 4.0},
    {"自年首周数", "WeekOfYear", "", 1, CT_NUM, NULL, 4.0},
    {"日", "day", "", 1, CT_NUM, NULL, 5.0},
    {"小时", "hour", "", 1, CT_NUM, NULL, 6.0},
    {"分钟", "minute", "", 1, CT_NUM, NULL, 7.0},
    {"秒", "second", "", 1, CT_NUM, NULL, 8.0},
    {"星期几", "DayOfWeek", "", 1, CT_NUM, NULL, 9.0},
    {"自年首天数", "DayOfYear", "", 1, CT_NUM, NULL, 10.0},
    {"确认钮", "BtnOKOnly", "“信息框”命令使用。", 1, CT_NUM, NULL, 0.0},
    {"确认取消钮", "BtnOKCancel", "", 1, CT_NUM, NULL, 1.0},
    {"放弃重试忽略钮", "BtnAbortRetryIgnore", "", 1, CT_NUM, NULL, 2.0},
    {"取消是否钮", "BtnYesNoCancel", "", 1, CT_NUM, NULL, 3.0},
    {"是否钮", "BtnYesNo", "", 1, CT_NUM, NULL, 4.0},
    {"重试取消钮", "BtnRetryCancel", "", 1, CT_NUM, NULL, 5.0},
    {"错误图标", "IcnCritical", "", 1, CT_NUM, NULL, 16.0},
    {"询问图标", "IcnQuestion", "", 1, CT_NUM, NULL, 32.0},
    {"警告图标", "IcnExclamation", "", 1, CT_NUM, NULL, 48.0},
    {"信息图标", "IcnInformation", "", 1, CT_NUM, NULL, 64.0},
    {"默认按钮一", "BtnDefault1", "", 1, CT_NUM, NULL, 0.0},
    {"默认按钮二", "BtnDefault2", "", 1, CT_NUM, NULL, 256.0},
    {"默认按钮三", "BtnDefault3", "", 1, CT_NUM, NULL, 512.0},
    {"默认按钮四", "BtnDefault4", "", 1, CT_NUM, NULL, 768.0},
    {"程序等待", "BoxAppModal", "", 1, CT_NUM, NULL, 0.0},
    {"系统等待", "BoxSysModal", "", 1, CT_NUM, NULL, 4096.0},
    {"位于前台", "BoxForeground", "", 1, CT_NUM, NULL, 65536.0},
    {"文本右对齐", "BoxRightAlign", "", 1, CT_NUM, NULL, 524288.0},
    {"取消钮", "btnCancel", "", 1, CT_NUM, NULL, 1.0},
    {"放弃钮", "btnAbort", "", 1, CT_NUM, NULL, 2.0},
    {"重试钮", "btnRetry", "", 1, CT_NUM, NULL, 3.0},
    {"忽略钮", "btnIgnore", "", 1, CT_NUM, NULL, 4.0},
    {"是钮", "btnYes", "", 1, CT_NUM, NULL, 5.0},
    {"否钮", "btnNo", "", 1, CT_NUM, NULL, 6.0},
    {"首拼及全拼", "", "", 1, CT_NUM, NULL, 1.0},
    {"双拼", "", "", 1, CT_NUM, NULL, 2.0},
    {"自动判别", "", "", 1, CT_NUM, NULL, 3.0},
    {"Ctrl键状态", "", "功能键状态常量。用于在按键事件中通过“位与”判断 Ctrl 是否同时按下。", 1, CT_NUM, NULL, 1.0},
    {"Shift键状态", "", "功能键状态常量。用于在按键事件中通过“位与”判断 Shift 是否同时按下。", 1, CT_NUM, NULL, 2.0},
    {"Alt键状态", "", "功能键状态常量。用于在按键事件中通过“位与”判断 Alt 是否同时按下。", 1, CT_NUM, NULL, 4.0},
    {"键0", "", "按键代码值。", 1, CT_NUM, NULL, 48.0},
    {"键1", "", "", 1, CT_NUM, NULL, 49.0},
    {"键2", "", "", 1, CT_NUM, NULL, 50.0},
    {"键3", "", "", 1, CT_NUM, NULL, 51.0},
    {"键4", "", "", 1, CT_NUM, NULL, 52.0},
    {"键5", "", "", 1, CT_NUM, NULL, 53.0},
    {"键6", "", "", 1, CT_NUM, NULL, 54.0},
    {"键7", "", "", 1, CT_NUM, NULL, 55.0},
    {"键8", "", "", 1, CT_NUM, NULL, 56.0},
    {"键9", "", "", 1, CT_NUM, NULL, 57.0},
    {"A键", "", "", 1, CT_NUM, NULL, 65.0},
    {"B键", "", "", 1, CT_NUM, NULL, 66.0},
    {"C键", "", "", 1, CT_NUM, NULL, 67.0},
    {"D键", "", "", 1, CT_NUM, NULL, 68.0},
    {"E键", "", "", 1, CT_NUM, NULL, 69.0},
    {"F键", "", "", 1, CT_NUM, NULL, 70.0},
    {"G键", "", "", 1, CT_NUM, NULL, 71.0},
    {"H键", "", "", 1, CT_NUM, NULL, 72.0},
    {"I键", "", "", 1, CT_NUM, NULL, 73.0},
    {"J键", "", "", 1, CT_NUM, NULL, 74.0},
    {"K键", "", "", 1, CT_NUM, NULL, 75.0},
    {"L键", "", "", 1, CT_NUM, NULL, 76.0},
    {"M键", "", "", 1, CT_NUM, NULL, 77.0},
    {"N键", "", "", 1, CT_NUM, NULL, 78.0},
    {"O键", "", "", 1, CT_NUM, NULL, 79.0},
    {"P键", "", "", 1, CT_NUM, NULL, 80.0},
    {"Q键", "", "", 1, CT_NUM, NULL, 81.0},
    {"R键", "", "", 1, CT_NUM, NULL, 82.0},
    {"S键", "", "", 1, CT_NUM, NULL, 83.0},
    {"T键", "", "", 1, CT_NUM, NULL, 84.0},
    {"U键", "", "", 1, CT_NUM, NULL, 85.0},
    {"V键", "", "", 1, CT_NUM, NULL, 86.0},
    {"W键", "", "", 1, CT_NUM, NULL, 87.0},
    {"X键", "", "", 1, CT_NUM, NULL, 88.0},
    {"Y键", "", "", 1, CT_NUM, NULL, 89.0},
    {"Z键", "", "", 1, CT_NUM, NULL, 90.0},
    {"F1键", "", "键常量值，等同于 Windows 虚拟键 VK_F1。", 1, CT_NUM, NULL, 112.0},
    {"F2键", "", "键常量值，等同于 Windows 虚拟键 VK_F2。", 1, CT_NUM, NULL, 113.0},
    {"F3键", "", "键常量值，等同于 Windows 虚拟键 VK_F3。", 1, CT_NUM, NULL, 114.0},
    {"F4键", "", "键常量值，等同于 Windows 虚拟键 VK_F4。", 1, CT_NUM, NULL, 115.0},
    {"F5键", "", "键常量值，等同于 Windows 虚拟键 VK_F5。", 1, CT_NUM, NULL, 116.0},
    {"F6键", "", "键常量值，等同于 Windows 虚拟键 VK_F6。", 1, CT_NUM, NULL, 117.0},
    {"F7键", "", "键常量值，等同于 Windows 虚拟键 VK_F7。", 1, CT_NUM, NULL, 118.0},
    {"F8键", "", "键常量值，等同于 Windows 虚拟键 VK_F8。", 1, CT_NUM, NULL, 119.0},
    {"F9键", "", "键常量值，等同于 Windows 虚拟键 VK_F9。", 1, CT_NUM, NULL, 120.0},
    {"F10键", "", "键常量值，等同于 Windows 虚拟键 VK_F10。", 1, CT_NUM, NULL, 121.0},
    {"F11键", "", "键常量值，等同于 Windows 虚拟键 VK_F11。", 1, CT_NUM, NULL, 122.0},
    {"F12键", "", "键常量值，等同于 Windows 虚拟键 VK_F12。", 1, CT_NUM, NULL, 123.0},
    {"F13键", "", "键常量值，等同于 Windows 虚拟键 VK_F13。", 1, CT_NUM, NULL, 124.0},
    {"F14键", "", "键常量值，等同于 Windows 虚拟键 VK_F14。", 1, CT_NUM, NULL, 125.0},
    {"F15键", "", "键常量值，等同于 Windows 虚拟键 VK_F15。", 1, CT_NUM, NULL, 126.0},
    {"F16键", "", "键常量值，等同于 Windows 虚拟键 VK_F16。", 1, CT_NUM, NULL, 127.0},
    {"Break键", "", "", 1, CT_NUM, NULL, 3.0},
    {"退格键", "", "", 1, CT_NUM, NULL, 8.0},
    {"Tab键", "", "键常量值，等同于 Windows 虚拟键 VK_TAB。", 1, CT_NUM, NULL, 9.0},
    {"回车键", "", "键常量值，等同于 Windows 虚拟键 VK_RETURN。", 1, CT_NUM, NULL, 13.0},
    {"Shift键", "", "键常量值，等同于 Windows 虚拟键 VK_SHIFT。", 1, CT_NUM, NULL, 16.0},
    {"Ctrl键", "", "键常量值，等同于 Windows 虚拟键 VK_CONTROL。", 1, CT_NUM, NULL, 17.0},
    {"Alt键", "", "键常量值，等同于 Windows 虚拟键 VK_MENU。", 1, CT_NUM, NULL, 18.0},
    {"Pause键", "", "", 1, CT_NUM, NULL, 19.0},
    {"CapsLock键", "", "", 1, CT_NUM, NULL, 20.0},
    {"NumLock键", "", "", 1, CT_NUM, NULL, 144.0},
    {"ScrollLock键", "", "", 1, CT_NUM, NULL, 145.0},
    {"Esc键", "", "键常量值，等同于 Windows 虚拟键 VK_ESCAPE。", 1, CT_NUM, NULL, 27.0},
    {"空格键", "", "键常量值，等同于 Windows 虚拟键 VK_SPACE。", 1, CT_NUM, NULL, 32.0},
    {"PageUp键", "", "", 1, CT_NUM, NULL, 33.0},
    {"PageDown键", "", "", 1, CT_NUM, NULL, 34.0},
    {"Home键", "", "", 1, CT_NUM, NULL, 36.0},
    {"End键", "", "", 1, CT_NUM, NULL, 35.0},
    {"左光标键", "", "", 1, CT_NUM, NULL, 37.0},
    {"上光标键", "", "", 1, CT_NUM, NULL, 38.0},
    {"右光标键", "", "", 1, CT_NUM, NULL, 39.0},
    {"下光标键", "", "", 1, CT_NUM, NULL, 40.0},
    {"Ins键", "", "", 1, CT_NUM, NULL, 45.0},
    {"Del键", "", "", 1, CT_NUM, NULL, 46.0},
    {"分号键", "", "", 1, CT_NUM, NULL, 186.0},
    {"等号键", "", "", 1, CT_NUM, NULL, 187.0},
    {"逗号键", "", "", 1, CT_NUM, NULL, 188.0},
    {"减号键", "", "", 1, CT_NUM, NULL, 189.0},
    {"圆点键", "", "", 1, CT_NUM, NULL, 190.0},
    {"除号键", "", "", 1, CT_NUM, NULL, 191.0},
    {"反撇号键", "", "", 1, CT_NUM, NULL, 192.0},
    {"左中括号键", "", "", 1, CT_NUM, NULL, 219.0},
    {"右中括号键", "", "", 1, CT_NUM, NULL, 221.0},
    {"斜杠键", "", "", 1, CT_NUM, NULL, 220.0},
    {"单引号键", "", "", 1, CT_NUM, NULL, 222.0},
    {"顶层", "top", "在窗口 Z 顺序的最前面。", 1, CT_NUM, NULL, 0.0},
    {"底层", "bottom", "在窗口 Z 顺序的最后面。", 1, CT_NUM, NULL, 0.0},
    {"最高层", "TopMost", "在所有现行窗口的最前面并一直保持此位置。", 1, CT_NUM, NULL, 0.0},
    {"次高层", "NoTopMost", "在最高层窗口的下面但在其他窗口的前面。", 1, CT_NUM, NULL, 0.0},
    {"全部转换", "", "", 1, CT_NUM, NULL, 1.0},
    {"日期部分", "", "", 1, CT_NUM, NULL, 2.0},
    {"时间部分", "", "", 1, CT_NUM, NULL, 3.0},
    {"输入文本", "", "", 1, CT_NUM, NULL, 1.0},
    {"输入整数", "", "", 1, CT_NUM, NULL, 2.0},
    {"输入小数", "", "", 1, CT_NUM, NULL, 3.0},
    {"拷贝", "", "", 1, CT_NUM, NULL, 1.0},
    {"翻转拷贝", "", "", 1, CT_NUM, NULL, 2.0},
    {"位异或", "", "", 1, CT_NUM, NULL, 3.0},
    {"位或", "", "", 1, CT_NUM, NULL, 4.0},
    {"位与", "", "", 1, CT_NUM, NULL, 5.0},
    {"从上到下", "", "", 1, CT_NUM, NULL, 1.0},
    {"从左到右", "", "", 1, CT_NUM, NULL, 2.0},
    {"从左上到右下", "", "", 1, CT_NUM, NULL, 3.0},
    {"从右上到左下", "", "", 1, CT_NUM, NULL, 4.0},
    {"从下到上", "", "", 1, CT_NUM, NULL, 5.0},
    {"从右到左", "", "", 1, CT_NUM, NULL, 6.0},
    {"从右下到左上", "", "", 1, CT_NUM, NULL, 7.0},
    {"从左下到右上", "", "", 1, CT_NUM, NULL, 8.0},
    {"字节集型", "bin", "可以存储大量的不定长字节数据。", 1, CT_NUM, NULL, 0.0},
    {"备注型", "memo", "文本型的扩充，可以存储大量的不定长文本数据。", 1, CT_NUM, NULL, 0.0},
    {"通常索引", "", "", 1, CT_NUM, NULL, 1.0},
    {"读音索引", "", "", 1, CT_NUM, NULL, 2.0},
    {"南方读音索引", "", "", 1, CT_NUM, NULL, 3.0},
    {"不区分大小写", "", "", 1, CT_NUM, NULL, 1.0},
    {"忽略所有空格", "", "", 1, CT_NUM, NULL, 2.0},
    {"取平均值", "", "", 1, CT_NUM, NULL, 1.0},
    {"求和", "", "", 1, CT_NUM, NULL, 2.0},
    {"取最大值", "", "取最大数值及日期。", 1, CT_NUM, NULL, 0.0},
    {"取最小值", "", "取最小数值及日期。", 1, CT_NUM, NULL, 0.0},
    {"禁止修改", "", "如果禁止修改，则自动禁止添加和删除。", 1, CT_NUM, NULL, 0.0},
    {"禁止添加", "", "", 1, CT_NUM, NULL, 2.0},
    {"禁止删除", "", "", 1, CT_NUM, NULL, 4.0},
    {"禁止自动判断", "", "", 1, CT_NUM, NULL, 8.0},
    {"根类", "", "具体注册表键名为: HKEY_CLASSES_ROOT。", 1, CT_NUM, NULL, 0.0},
    {"现行设置", "", "具体注册表键名为: HKEY_CURRENT_CONFIG。", 1, CT_NUM, NULL, 0.0},
    {"现行用户", "", "具体注册表键名为: HKEY_CURRENT_USER。", 1, CT_NUM, NULL, 0.0},
    {"本地机器", "", "具体注册表键名为: HKEY_LOCAL_MACHINE。", 1, CT_NUM, NULL, 0.0},
    {"所有用户", "", "具体注册表键名为: HKEY_USERS。", 1, CT_NUM, NULL, 0.0},
    {"单击左键", "", "", 1, CT_NUM, NULL, 1.0},
    {"双击", "", "", 1, CT_NUM, NULL, 2.0},
    {"单击右键", "", "", 1, CT_NUM, NULL, 3.0},
    {"默认色", "", "", 1, CT_NUM, NULL, -16777216.0},
    {"文本", "", "", 1, CT_NUM, NULL, 1.0},
    {"图片文件名", "", "", 1, CT_NUM, NULL, 2.0},
    {"图片数据", "", "", 1, CT_NUM, NULL, 3.0},
    {"字节集数据", "", "", 1, CT_NUM, NULL, 4.0},
    {"上左", "", "", 1, CT_NUM, NULL, 1.0},
    {"上中", "", "", 1, CT_NUM, NULL, 2.0},
    {"上右", "", "", 1, CT_NUM, NULL, 3.0},
    {"中左", "", "", 1, CT_NUM, NULL, 4.0},
    {"中中", "", "", 1, CT_NUM, NULL, 5.0},
    {"中右", "", "", 1, CT_NUM, NULL, 6.0},
    {"下左", "", "", 1, CT_NUM, NULL, 7.0},
    {"下中", "", "", 1, CT_NUM, NULL, 8.0},
    {"下右", "", "", 1, CT_NUM, NULL, 9.0},
    {"缩放图片", "", "", 1, CT_NUM, NULL, 10.0},
    {"居中图片", "", "", 1, CT_NUM, NULL, 11.0},
    {"缩放居中图片", "", "", 1, CT_NUM, NULL, 12.0},
    {"平铺图片", "", "", 1, CT_NUM, NULL, 13.0},
    {"缩放平铺图片", "", "", 1, CT_NUM, NULL, 14.0},
    {"粗体", "", "", 1, CT_NUM, NULL, 1.0},
    {"斜体", "", "", 1, CT_NUM, NULL, 2.0},
    {"下划线", "", "", 1, CT_NUM, NULL, 4.0},
    {"删除线", "", "", 1, CT_NUM, NULL, 8.0},
    {"通常型", "", "", 1, CT_NUM, NULL, 0.0},
    {"左边框", "", "", 1, CT_NUM, NULL, 1.0},
    {"上边框", "", "", 1, CT_NUM, NULL, 2.0},
    {"右边框", "", "", 1, CT_NUM, NULL, 4.0},
    {"下边框", "", "", 1, CT_NUM, NULL, 8.0},
    {"水平线", "", "", 1, CT_NUM, NULL, 16.0},
    {"垂直线", "", "", 1, CT_NUM, NULL, 32.0},
    {"单斜线", "", "", 1, CT_NUM, NULL, 64.0},
    {"双斜线", "", "", 1, CT_NUM, NULL, 128.0},
    {"交叉线", "", "", 1, CT_NUM, NULL, 256.0},
    {"左单元格", "", "", 1, CT_NUM, NULL, 1.0},
    {"上单元格", "", "", 1, CT_NUM, NULL, 2.0},
    {"右单元格", "", "", 1, CT_NUM, NULL, 3.0},
    {"下单元格", "", "", 1, CT_NUM, NULL, 4.0},
    {"无页号", "", "", 1, CT_NUM, NULL, 0.0},
    {"上左页号", "", "", 1, CT_NUM, NULL, 1.0},
    {"上中页号", "", "", 1, CT_NUM, NULL, 2.0},
    {"上右页号", "", "", 1, CT_NUM, NULL, 3.0},
    {"下左页号", "", "", 1, CT_NUM, NULL, 4.0},
    {"下中页号", "", "", 1, CT_NUM, NULL, 5.0},
    {"下右页号", "", "", 1, CT_NUM, NULL, 6.0},
    {"全部页", "", "", 1, CT_NUM, NULL, 0.0},
    {"仅打印奇数页", "", "", 1, CT_NUM, NULL, 1.0},
    {"仅打印偶数页", "", "", 1, CT_NUM, NULL, 2.0},
    {"页范围", "", "", 1, CT_NUM, NULL, 1.0},
    {"行范围", "", "", 1, CT_NUM, NULL, 2.0},
    {"纵向", "", "", 1, CT_NUM, NULL, 0.0},
    {"横向", "", "", 1, CT_NUM, NULL, 1.0},
    {"默认纸", "", "", 1, CT_NUM, NULL, 0.0},
    {"A3纸", "", "297 x 420 毫米。", 1, CT_NUM, NULL, 0.0},
    {"A4纸", "", "210 x 297 毫米。", 1, CT_NUM, NULL, 0.0},
    {"A5纸", "", "148 x 210 毫米。", 1, CT_NUM, NULL, 0.0},
    {"B4纸", "", "250 x 354 毫米。", 1, CT_NUM, NULL, 0.0},
    {"B5纸", "", "182 x 257 毫米。", 1, CT_NUM, NULL, 0.0},
    {"四开", "", "215 x 275 毫米。", 1, CT_NUM, NULL, 0.0},
    {"十六开", "", "146 x 215 毫米。", 1, CT_NUM, NULL, 0.0},
    {"三十二开", "", "97 x 151 毫米。", 1, CT_NUM, NULL, 0.0},
    {"信纸", "", "216 x 279 毫米。", 1, CT_NUM, NULL, 0.0},
    {"法律用纸", "", "216 x 355 毫米。", 1, CT_NUM, NULL, 0.0},
    {"行政用纸", "", "184 x 266 毫米。", 1, CT_NUM, NULL, 0.0},
    {"声明", "", "140 x 216 毫米。", 1, CT_NUM, NULL, 0.0},
    {"小报", "", "279 x 432 毫米。", 1, CT_NUM, NULL, 0.0},
    {"笔记", "", "216 x 279 毫米。", 1, CT_NUM, NULL, 0.0},
    {"帐本", "", "432 x 279 毫米。", 1, CT_NUM, NULL, 0.0},
    {"对开纸", "", "216 x 330 毫米。", 1, CT_NUM, NULL, 0.0},
    {"输入密码", "", "", 1, CT_NUM, NULL, 4.0},
    {"缩放到纸宽", "", "", 1, CT_NUM, NULL, -1.0},
    {"限定到纸宽", "", "", 1, CT_NUM, NULL, -2.0},
    {"常量", "", "", 1, CT_NUM, NULL, 0.0},
    {"资源", "", "", 1, CT_NUM, NULL, 1.0},
    {"清除信号", "", "", 1, CT_NUM, NULL, 1.0},
    {"发送或置位", "", "", 1, CT_NUM, NULL, 2.0},
    {"DTR信号", "", "", 1, CT_NUM, NULL, 1.0},
    {"RTS信号", "", "", 1, CT_NUM, NULL, 2.0},
    {"Break信号", "", "", 1, CT_NUM, NULL, 3.0},
    {"GBK中文", "", "", 1, CT_NUM, NULL, 1.0},
    {"英文", "", "", 1, CT_NUM, NULL, 2.0},
    {"BIG5中文", "", "", 1, CT_NUM, NULL, 3.0},
    {"标准输出设备", "", "", 1, CT_NUM, NULL, 1.0},
    {"标准错误设备", "", "", 1, CT_NUM, NULL, 2.0},
    {"无法载入的常量", "", "如果源程序中的某一库定义常量由于其所在支持库载入出错而导致无法被载入，将自动被本常量所取代。", 1, CT_NUM, NULL, 0.0},
    {"横向绘画单位", "", "", 1, CT_NUM, NULL, 1.0},
    {"纵向绘画单位", "", "", 1, CT_NUM, NULL, 2.0},
    {"横向像素单位", "", "", 1, CT_NUM, NULL, 3.0},
    {"纵向像素单位", "", "", 1, CT_NUM, NULL, 4.0},
};

int g_ConstInfo_krnln_global_var_count = 335;

#endif
